[package]
name = "chip8-rs"
version = "0.1.0"
authors = ["saging"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
clap = "2.33.0"
minifb = "0.12.0"